/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OptimisticOracleV3Interface } from "./OptimisticOracleV3Interface";
export type { UMAInputOracle } from "./UMAInputOracle";
