/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OptimisticOracleV3InterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "assertTruth" | "defaultIdentifier" | "settleAssertion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assertTruth",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultIdentifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleAssertion",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assertTruth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAssertion",
    data: BytesLike
  ): Result;
}

export interface OptimisticOracleV3Interface extends BaseContract {
  connect(runner?: ContractRunner | null): OptimisticOracleV3Interface;
  waitForDeployment(): Promise<this>;

  interface: OptimisticOracleV3InterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assertTruth: TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike,
      domain: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  defaultIdentifier: TypedContractMethod<[], [string], "view">;

  settleAssertion: TypedContractMethod<
    [assertionId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assertTruth"
  ): TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike,
      domain: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultIdentifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settleAssertion"
  ): TypedContractMethod<[assertionId: BytesLike], [boolean], "nonpayable">;

  filters: {};
}
