/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UMAInputOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assertDataFor"
      | "assertionDisputedCallback"
      | "assertionLiveness"
      | "assertionResolvedCallback"
      | "assertionsData"
      | "bond"
      | "defaultCurrency"
      | "defaultIdentifier"
      | "domain"
      | "latest"
      | "latestAssertionByDataId"
      | "latestResolved"
      | "oo"
      | "owner"
      | "renounceOwnership"
      | "resolvedDataById"
      | "setAssertionLiveness"
      | "setBond"
      | "setDefaultCurrency"
      | "setDomain"
      | "setOracle"
      | "settle"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssertionCreated"
      | "AssertionResolved"
      | "ConfigUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assertDataFor",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assertionDisputedCallback",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assertionLiveness",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assertionResolvedCallback",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "assertionsData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "bond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultIdentifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "domain", values?: undefined): string;
  encodeFunctionData(functionFragment: "latest", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "latestAssertionByDataId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestResolved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "oo", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolvedDataById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssertionLiveness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultCurrency",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDomain",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "settle", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assertDataFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assertionDisputedCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assertionLiveness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assertionResolvedCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assertionsData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestAssertionByDataId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestResolved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvedDataById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssertionLiveness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDomain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AssertionCreatedEvent {
  export type InputTuple = [
    dataId: BytesLike,
    assertionId: BytesLike,
    asserter: AddressLike,
    data: BytesLike,
    liveness: BigNumberish,
    bond: BigNumberish
  ];
  export type OutputTuple = [
    dataId: string,
    assertionId: string,
    asserter: string,
    data: string,
    liveness: bigint,
    bond: bigint
  ];
  export interface OutputObject {
    dataId: string;
    assertionId: string;
    asserter: string;
    data: string;
    liveness: bigint;
    bond: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssertionResolvedEvent {
  export type InputTuple = [
    dataId: BytesLike,
    assertionId: BytesLike,
    assertedTruthfully: boolean,
    data: BytesLike
  ];
  export type OutputTuple = [
    dataId: string,
    assertionId: string,
    assertedTruthfully: boolean,
    data: string
  ];
  export interface OutputObject {
    dataId: string;
    assertionId: string;
    assertedTruthfully: boolean;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    defaultCurrency: AddressLike,
    oo: AddressLike,
    assertionLiveness: BigNumberish,
    bond: BigNumberish,
    defaultIdentifier: BytesLike,
    domain: BytesLike
  ];
  export type OutputTuple = [
    defaultCurrency: string,
    oo: string,
    assertionLiveness: bigint,
    bond: bigint,
    defaultIdentifier: string,
    domain: string
  ];
  export interface OutputObject {
    defaultCurrency: string;
    oo: string;
    assertionLiveness: bigint;
    bond: bigint;
    defaultIdentifier: string;
    domain: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UMAInputOracle extends BaseContract {
  connect(runner?: ContractRunner | null): UMAInputOracle;
  waitForDeployment(): Promise<this>;

  interface: UMAInputOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assertDataFor: TypedContractMethod<
    [dataId: BytesLike, data: BytesLike, asserter: AddressLike],
    [string],
    "nonpayable"
  >;

  assertionDisputedCallback: TypedContractMethod<
    [arg0: BytesLike],
    [void],
    "view"
  >;

  assertionLiveness: TypedContractMethod<[], [bigint], "view">;

  assertionResolvedCallback: TypedContractMethod<
    [assertionId: BytesLike, assertedTruthfully: boolean],
    [void],
    "nonpayable"
  >;

  assertionsData: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, boolean] & {
        dataId: string;
        data: string;
        asserter: string;
        resolved: boolean;
        truthfully: boolean;
      }
    ],
    "view"
  >;

  bond: TypedContractMethod<[], [bigint], "view">;

  defaultCurrency: TypedContractMethod<[], [string], "view">;

  defaultIdentifier: TypedContractMethod<[], [string], "view">;

  domain: TypedContractMethod<[], [string], "view">;

  latest: TypedContractMethod<
    [dataId: BytesLike],
    [
      [boolean, boolean, string, string] & {
        isResolved: boolean;
        truthfully: boolean;
        data: string;
        assertionId: string;
      }
    ],
    "view"
  >;

  latestAssertionByDataId: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  latestResolved: TypedContractMethod<[dataId: BytesLike], [string], "view">;

  oo: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolvedDataById: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  setAssertionLiveness: TypedContractMethod<
    [newLiveness: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBond: TypedContractMethod<[newBond: BigNumberish], [void], "nonpayable">;

  setDefaultCurrency: TypedContractMethod<
    [newCurrency: AddressLike],
    [void],
    "nonpayable"
  >;

  setDomain: TypedContractMethod<[newDomain: BytesLike], [void], "nonpayable">;

  setOracle: TypedContractMethod<[newOO: AddressLike], [void], "nonpayable">;

  settle: TypedContractMethod<
    [assertionId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assertDataFor"
  ): TypedContractMethod<
    [dataId: BytesLike, data: BytesLike, asserter: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assertionDisputedCallback"
  ): TypedContractMethod<[arg0: BytesLike], [void], "view">;
  getFunction(
    nameOrSignature: "assertionLiveness"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assertionResolvedCallback"
  ): TypedContractMethod<
    [assertionId: BytesLike, assertedTruthfully: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assertionsData"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, boolean] & {
        dataId: string;
        data: string;
        asserter: string;
        resolved: boolean;
        truthfully: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultCurrency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultIdentifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "domain"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "latest"
  ): TypedContractMethod<
    [dataId: BytesLike],
    [
      [boolean, boolean, string, string] & {
        isResolved: boolean;
        truthfully: boolean;
        data: string;
        assertionId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestAssertionByDataId"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "latestResolved"
  ): TypedContractMethod<[dataId: BytesLike], [string], "view">;
  getFunction(nameOrSignature: "oo"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolvedDataById"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setAssertionLiveness"
  ): TypedContractMethod<[newLiveness: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBond"
  ): TypedContractMethod<[newBond: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultCurrency"
  ): TypedContractMethod<[newCurrency: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDomain"
  ): TypedContractMethod<[newDomain: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOO: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[assertionId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssertionCreated"
  ): TypedContractEvent<
    AssertionCreatedEvent.InputTuple,
    AssertionCreatedEvent.OutputTuple,
    AssertionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AssertionResolved"
  ): TypedContractEvent<
    AssertionResolvedEvent.InputTuple,
    AssertionResolvedEvent.OutputTuple,
    AssertionResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AssertionCreated(bytes32,bytes32,address,bytes32,uint64,uint256)": TypedContractEvent<
      AssertionCreatedEvent.InputTuple,
      AssertionCreatedEvent.OutputTuple,
      AssertionCreatedEvent.OutputObject
    >;
    AssertionCreated: TypedContractEvent<
      AssertionCreatedEvent.InputTuple,
      AssertionCreatedEvent.OutputTuple,
      AssertionCreatedEvent.OutputObject
    >;

    "AssertionResolved(bytes32,bytes32,bool,bytes32)": TypedContractEvent<
      AssertionResolvedEvent.InputTuple,
      AssertionResolvedEvent.OutputTuple,
      AssertionResolvedEvent.OutputObject
    >;
    AssertionResolved: TypedContractEvent<
      AssertionResolvedEvent.InputTuple,
      AssertionResolvedEvent.OutputTuple,
      AssertionResolvedEvent.OutputObject
    >;

    "ConfigUpdated(address,address,uint64,uint256,bytes32,bytes32)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
