services:
  - type: web
    name: map-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn map_dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 