/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExternalOracle,
  IExternalOracleInterface,
} from "../../../contracts/NatureIndexTracker.sol/IExternalOracle";

const _abi = [
  {
    inputs: [],
    name: "latest",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IExternalOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IExternalOracleInterface {
    return new Interface(_abi) as IExternalOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IExternalOracle {
    return new Contract(address, _abi, runner) as unknown as IExternalOracle;
  }
}
