/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGeoIndexToken,
  IGeoIndexTokenInterface,
} from "../../../contracts/NatureIndexTracker.sol/IGeoIndexToken";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGeoIndexToken__factory {
  static readonly abi = _abi;
  static createInterface(): IGeoIndexTokenInterface {
    return new Interface(_abi) as IGeoIndexTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGeoIndexToken {
    return new Contract(address, _abi, runner) as unknown as IGeoIndexToken;
  }
}
