/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OptimisticOracleV3Interface__factory } from "./OptimisticOracleV3Interface__factory";
export { UMAInputOracle__factory } from "./UMAInputOracle__factory";
