/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OptimisticOracleV3Interface,
  OptimisticOracleV3InterfaceInterface,
} from "../../../contracts/UMAInputOracle.sol/OptimisticOracleV3Interface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "claim",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "asserter",
        type: "address",
      },
      {
        internalType: "address",
        name: "callbackRecipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "escalationManager",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "liveness",
        type: "uint64",
      },
      {
        internalType: "contract IERC20",
        name: "currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bond",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "domain",
        type: "bytes32",
      },
    ],
    name: "assertTruth",
    outputs: [
      {
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultIdentifier",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
    ],
    name: "settleAssertion",
    outputs: [
      {
        internalType: "bool",
        name: "assertedTruthfully",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class OptimisticOracleV3Interface__factory {
  static readonly abi = _abi;
  static createInterface(): OptimisticOracleV3InterfaceInterface {
    return new Interface(_abi) as OptimisticOracleV3InterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OptimisticOracleV3Interface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as OptimisticOracleV3Interface;
  }
}
