/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarbonIndex,
  ICarbonIndexInterface,
} from "../../../contracts/InputOracle.sol/ICarbonIndex";

const _abi = [
  {
    inputs: [],
    name: "getIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICarbonIndex__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonIndexInterface {
    return new Interface(_abi) as ICarbonIndexInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarbonIndex {
    return new Contract(address, _abi, runner) as unknown as ICarbonIndex;
  }
}
