/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICarbonIndex__factory } from "./ICarbonIndex__factory";
export { InputOracle__factory } from "./InputOracle__factory";
