/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InputOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dataSource"
      | "latest"
      | "multiplier"
      | "owner"
      | "renounceOwnership"
      | "setDataSource"
      | "setMultiplier"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataSourceUpdated"
      | "MultiplierUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dataSource",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "latest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiplier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDataSource",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "dataSource", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiplier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDataSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DataSourceUpdatedEvent {
  export type InputTuple = [oldSource: AddressLike, newSource: AddressLike];
  export type OutputTuple = [oldSource: string, newSource: string];
  export interface OutputObject {
    oldSource: string;
    newSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiplierUpdatedEvent {
  export type InputTuple = [
    oldMultiplier: BigNumberish,
    newMultiplier: BigNumberish
  ];
  export type OutputTuple = [oldMultiplier: bigint, newMultiplier: bigint];
  export interface OutputObject {
    oldMultiplier: bigint;
    newMultiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InputOracle extends BaseContract {
  connect(runner?: ContractRunner | null): InputOracle;
  waitForDeployment(): Promise<this>;

  interface: InputOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dataSource: TypedContractMethod<[], [string], "view">;

  latest: TypedContractMethod<[], [bigint], "view">;

  multiplier: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDataSource: TypedContractMethod<
    [newSource: AddressLike],
    [void],
    "nonpayable"
  >;

  setMultiplier: TypedContractMethod<
    [newMultiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dataSource"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "latest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "multiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDataSource"
  ): TypedContractMethod<[newSource: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMultiplier"
  ): TypedContractMethod<[newMultiplier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DataSourceUpdated"
  ): TypedContractEvent<
    DataSourceUpdatedEvent.InputTuple,
    DataSourceUpdatedEvent.OutputTuple,
    DataSourceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MultiplierUpdated"
  ): TypedContractEvent<
    MultiplierUpdatedEvent.InputTuple,
    MultiplierUpdatedEvent.OutputTuple,
    MultiplierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DataSourceUpdated(address,address)": TypedContractEvent<
      DataSourceUpdatedEvent.InputTuple,
      DataSourceUpdatedEvent.OutputTuple,
      DataSourceUpdatedEvent.OutputObject
    >;
    DataSourceUpdated: TypedContractEvent<
      DataSourceUpdatedEvent.InputTuple,
      DataSourceUpdatedEvent.OutputTuple,
      DataSourceUpdatedEvent.OutputObject
    >;

    "MultiplierUpdated(uint256,uint256)": TypedContractEvent<
      MultiplierUpdatedEvent.InputTuple,
      MultiplierUpdatedEvent.OutputTuple,
      MultiplierUpdatedEvent.OutputObject
    >;
    MultiplierUpdated: TypedContractEvent<
      MultiplierUpdatedEvent.InputTuple,
      MultiplierUpdatedEvent.OutputTuple,
      MultiplierUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
