/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKVerify,
  IZKVerifyInterface,
} from "../../../contracts/interfaces/IZKVerify";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "proofId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "submitter",
        type: "address",
      },
    ],
    name: "ProofSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "proofId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    name: "ProofVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "proofId",
        type: "bytes32",
      },
    ],
    name: "getProofStatus",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "submitted",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "verified",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "submissionTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "verificationTime",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "errorMessage",
            type: "string",
          },
        ],
        internalType: "struct IZKVerify.ProofStatus",
        name: "status",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVerificationFee",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isAcceptingSubmissions",
    outputs: [
      {
        internalType: "bool",
        name: "accepting",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "publicInputs",
        type: "bytes",
      },
    ],
    name: "submitProof",
    outputs: [
      {
        internalType: "bytes32",
        name: "proofId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "proofId",
        type: "bytes32",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKVerify__factory {
  static readonly abi = _abi;
  static createInterface(): IZKVerifyInterface {
    return new Interface(_abi) as IZKVerifyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZKVerify {
    return new Contract(address, _abi, runner) as unknown as IZKVerify;
  }
}
