/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CarbonIndex {
  export type ProofMetadataStruct = {
    timestamp: BigNumberish;
    latMin: BigNumberish;
    latMax: BigNumberish;
    lonMin: BigNumberish;
    lonMax: BigNumberish;
    verifier: AddressLike;
    isActive: boolean;
  };

  export type ProofMetadataStructOutput = [
    timestamp: bigint,
    latMin: bigint,
    latMax: bigint,
    lonMin: bigint,
    lonMax: bigint,
    verifier: string,
    isActive: boolean
  ] & {
    timestamp: bigint;
    latMin: bigint;
    latMax: bigint;
    lonMin: bigint;
    lonMax: bigint;
    verifier: string;
    isActive: boolean;
  };
}

export declare namespace SP1Verifier {
  export type CarbonIndexProofStruct = {
    nhiScore: BigNumberish;
    p20Percentile: BigNumberish;
    p90Percentile: BigNumberish;
    gammaShape: BigNumberish;
    gammaScale: BigNumberish;
    gammaLoc: BigNumberish;
    carbonIndexValue: BigNumberish;
    timestamp: BigNumberish;
    latMin: BigNumberish;
    latMax: BigNumberish;
    lonMin: BigNumberish;
    lonMax: BigNumberish;
  };

  export type CarbonIndexProofStructOutput = [
    nhiScore: bigint,
    p20Percentile: bigint,
    p90Percentile: bigint,
    gammaShape: bigint,
    gammaScale: bigint,
    gammaLoc: bigint,
    carbonIndexValue: bigint,
    timestamp: bigint,
    latMin: bigint,
    latMax: bigint,
    lonMin: bigint,
    lonMax: bigint
  ] & {
    nhiScore: bigint;
    p20Percentile: bigint;
    p90Percentile: bigint;
    gammaShape: bigint;
    gammaScale: bigint;
    gammaLoc: bigint;
    carbonIndexValue: bigint;
    timestamp: bigint;
    latMin: bigint;
    latMax: bigint;
    lonMin: bigint;
    lonMax: bigint;
  };
}

export interface CarbonIndexInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateProof"
      | "getIndex"
      | "getIndexFromProof"
      | "getLatestVerifiedProof"
      | "getProofMetadata"
      | "isProofUsed"
      | "owner"
      | "proofMetadata"
      | "renounceOwnership"
      | "setIndex"
      | "sp1Verifier"
      | "transferOwnership"
      | "updateIndexWithProof"
      | "verifiedIndexValues"
      | "verifyAndUpdateIndex"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IndexUpdated"
      | "IndexUpdatedWithProof"
      | "OwnershipTransferred"
      | "ProofAccepted"
      | "ProofRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getIndexFromProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestVerifiedProof",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProofMetadata",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProofUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proofMetadata",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sp1Verifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIndexWithProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedIndexValues",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndUpdateIndex",
    values: [BytesLike, SP1Verifier.CarbonIndexProofStruct, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIndexFromProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestVerifiedProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProofMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProofUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proofMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sp1Verifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIndexWithProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedIndexValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndUpdateIndex",
    data: BytesLike
  ): Result;
}

export namespace IndexUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndexUpdatedWithProofEvent {
  export type InputTuple = [
    proofHash: BytesLike,
    oldValue: BigNumberish,
    newValue: BigNumberish,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    proofHash: string,
    oldValue: bigint,
    newValue: bigint,
    verifier: string
  ];
  export interface OutputObject {
    proofHash: string;
    oldValue: bigint;
    newValue: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofAcceptedEvent {
  export type InputTuple = [proofHash: BytesLike, indexValue: BigNumberish];
  export type OutputTuple = [proofHash: string, indexValue: bigint];
  export interface OutputObject {
    proofHash: string;
    indexValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofRejectedEvent {
  export type InputTuple = [proofHash: BytesLike, reason: string];
  export type OutputTuple = [proofHash: string, reason: string];
  export interface OutputObject {
    proofHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonIndex extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonIndex;
  waitForDeployment(): Promise<this>;

  interface: CarbonIndexInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getIndex: TypedContractMethod<[], [bigint], "view">;

  getIndexFromProof: TypedContractMethod<
    [proofHash: BytesLike],
    [bigint],
    "view"
  >;

  getLatestVerifiedProof: TypedContractMethod<
    [],
    [[string, bigint] & { proofHash: string; indexValue: bigint }],
    "view"
  >;

  getProofMetadata: TypedContractMethod<
    [proofHash: BytesLike],
    [CarbonIndex.ProofMetadataStructOutput],
    "view"
  >;

  isProofUsed: TypedContractMethod<[proofHash: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proofMetadata: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        timestamp: bigint;
        latMin: bigint;
        latMax: bigint;
        lonMin: bigint;
        lonMax: bigint;
        verifier: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setIndex: TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;

  sp1Verifier: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateIndexWithProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifiedIndexValues: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  verifyAndUpdateIndex: TypedContractMethod<
    [
      proof: BytesLike,
      publicValues: SP1Verifier.CarbonIndexProofStruct,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getIndexFromProof"
  ): TypedContractMethod<[proofHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestVerifiedProof"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { proofHash: string; indexValue: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofMetadata"
  ): TypedContractMethod<
    [proofHash: BytesLike],
    [CarbonIndex.ProofMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProofUsed"
  ): TypedContractMethod<[proofHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofMetadata"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        timestamp: bigint;
        latMin: bigint;
        latMax: bigint;
        lonMin: bigint;
        lonMax: bigint;
        verifier: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIndex"
  ): TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sp1Verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateIndexWithProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedIndexValues"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAndUpdateIndex"
  ): TypedContractMethod<
    [
      proof: BytesLike,
      publicValues: SP1Verifier.CarbonIndexProofStruct,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IndexUpdated"
  ): TypedContractEvent<
    IndexUpdatedEvent.InputTuple,
    IndexUpdatedEvent.OutputTuple,
    IndexUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IndexUpdatedWithProof"
  ): TypedContractEvent<
    IndexUpdatedWithProofEvent.InputTuple,
    IndexUpdatedWithProofEvent.OutputTuple,
    IndexUpdatedWithProofEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofAccepted"
  ): TypedContractEvent<
    ProofAcceptedEvent.InputTuple,
    ProofAcceptedEvent.OutputTuple,
    ProofAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "ProofRejected"
  ): TypedContractEvent<
    ProofRejectedEvent.InputTuple,
    ProofRejectedEvent.OutputTuple,
    ProofRejectedEvent.OutputObject
  >;

  filters: {
    "IndexUpdated(uint256,uint256)": TypedContractEvent<
      IndexUpdatedEvent.InputTuple,
      IndexUpdatedEvent.OutputTuple,
      IndexUpdatedEvent.OutputObject
    >;
    IndexUpdated: TypedContractEvent<
      IndexUpdatedEvent.InputTuple,
      IndexUpdatedEvent.OutputTuple,
      IndexUpdatedEvent.OutputObject
    >;

    "IndexUpdatedWithProof(bytes32,uint256,uint256,address)": TypedContractEvent<
      IndexUpdatedWithProofEvent.InputTuple,
      IndexUpdatedWithProofEvent.OutputTuple,
      IndexUpdatedWithProofEvent.OutputObject
    >;
    IndexUpdatedWithProof: TypedContractEvent<
      IndexUpdatedWithProofEvent.InputTuple,
      IndexUpdatedWithProofEvent.OutputTuple,
      IndexUpdatedWithProofEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofAccepted(bytes32,uint256)": TypedContractEvent<
      ProofAcceptedEvent.InputTuple,
      ProofAcceptedEvent.OutputTuple,
      ProofAcceptedEvent.OutputObject
    >;
    ProofAccepted: TypedContractEvent<
      ProofAcceptedEvent.InputTuple,
      ProofAcceptedEvent.OutputTuple,
      ProofAcceptedEvent.OutputObject
    >;

    "ProofRejected(bytes32,string)": TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;
    ProofRejected: TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;
  };
}
