/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as inputOracleSol from "./InputOracle.sol";
export type { inputOracleSol };
import type * as nftVaultSol from "./NFTVault.sol";
export type { nftVaultSol };
import type * as natureIndexTrackerSol from "./NatureIndexTracker.sol";
export type { natureIndexTrackerSol };
import type * as projectVaultSol from "./ProjectVault.sol";
export type { projectVaultSol };
import type * as rewardTokenSol from "./RewardToken.sol";
export type { rewardTokenSol };
import type * as umaInputOracleSol from "./UMAInputOracle.sol";
export type { umaInputOracleSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CarbonIndex } from "./CarbonIndex";
export type { GeoIndexToken } from "./GeoIndexToken";
export type { NFTFactory } from "./NFTFactory";
export type { ProjectNFT } from "./ProjectNFT";
export type { SP1Verifier } from "./SP1Verifier";
export type { VaultFactory } from "./VaultFactory";
