/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NFTFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createNFTCollection"
      | "deployedNFTs"
      | "factoryFee"
      | "getCollectionInfo"
      | "getDeployedNFTs"
      | "getNFTCreator"
      | "getNFTVault"
      | "getTotalCollections"
      | "isDeployedNFT"
      | "isDeployedVault"
      | "nftCreators"
      | "nftVaults"
      | "owner"
      | "renounceOwnership"
      | "setFactoryFee"
      | "transferOwnership"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FactoryFeeUpdated"
      | "NFTCollectionCreated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createNFTCollection",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedNFTs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployedVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftCreators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFactoryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createNFTCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factoryFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeployedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeployedVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftVaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFactoryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FactoryFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTCollectionCreatedEvent {
  export type InputTuple = [
    nftAddress: AddressLike,
    vaultAddress: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string,
    maxSupply: BigNumberish,
    mintPrice: BigNumberish
  ];
  export type OutputTuple = [
    nftAddress: string,
    vaultAddress: string,
    creator: string,
    name: string,
    symbol: string,
    maxSupply: bigint,
    mintPrice: bigint
  ];
  export interface OutputObject {
    nftAddress: string;
    vaultAddress: string;
    creator: string;
    name: string;
    symbol: string;
    maxSupply: bigint;
    mintPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NFTFactory;
  waitForDeployment(): Promise<this>;

  interface: NFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createNFTCollection: TypedContractMethod<
    [
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      baseURI: string
    ],
    [[string, string]],
    "payable"
  >;

  deployedNFTs: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  factoryFee: TypedContractMethod<[], [bigint], "view">;

  getCollectionInfo: TypedContractMethod<
    [nftAddress: AddressLike],
    [
      [string, string, boolean] & {
        creator: string;
        vault: string;
        hasVault: boolean;
      }
    ],
    "view"
  >;

  getDeployedNFTs: TypedContractMethod<[], [string[]], "view">;

  getNFTCreator: TypedContractMethod<
    [nftAddress: AddressLike],
    [string],
    "view"
  >;

  getNFTVault: TypedContractMethod<[nftAddress: AddressLike], [string], "view">;

  getTotalCollections: TypedContractMethod<[], [bigint], "view">;

  isDeployedNFT: TypedContractMethod<
    [nftAddress: AddressLike],
    [boolean],
    "view"
  >;

  isDeployedVault: TypedContractMethod<
    [vaultAddress: AddressLike],
    [boolean],
    "view"
  >;

  nftCreators: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  nftVaults: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFactoryFee: TypedContractMethod<
    [_factoryFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createNFTCollection"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      baseURI: string
    ],
    [[string, string]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deployedNFTs"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "factoryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCollectionInfo"
  ): TypedContractMethod<
    [nftAddress: AddressLike],
    [
      [string, string, boolean] & {
        creator: string;
        vault: string;
        hasVault: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeployedNFTs"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNFTCreator"
  ): TypedContractMethod<[nftAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getNFTVault"
  ): TypedContractMethod<[nftAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalCollections"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isDeployedNFT"
  ): TypedContractMethod<[nftAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDeployedVault"
  ): TypedContractMethod<[vaultAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nftCreators"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "nftVaults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFactoryFee"
  ): TypedContractMethod<[_factoryFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FactoryFeeUpdated"
  ): TypedContractEvent<
    FactoryFeeUpdatedEvent.InputTuple,
    FactoryFeeUpdatedEvent.OutputTuple,
    FactoryFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTCollectionCreated"
  ): TypedContractEvent<
    NFTCollectionCreatedEvent.InputTuple,
    NFTCollectionCreatedEvent.OutputTuple,
    NFTCollectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FactoryFeeUpdated(uint256)": TypedContractEvent<
      FactoryFeeUpdatedEvent.InputTuple,
      FactoryFeeUpdatedEvent.OutputTuple,
      FactoryFeeUpdatedEvent.OutputObject
    >;
    FactoryFeeUpdated: TypedContractEvent<
      FactoryFeeUpdatedEvent.InputTuple,
      FactoryFeeUpdatedEvent.OutputTuple,
      FactoryFeeUpdatedEvent.OutputObject
    >;

    "NFTCollectionCreated(address,address,address,string,string,uint256,uint256)": TypedContractEvent<
      NFTCollectionCreatedEvent.InputTuple,
      NFTCollectionCreatedEvent.OutputTuple,
      NFTCollectionCreatedEvent.OutputObject
    >;
    NFTCollectionCreated: TypedContractEvent<
      NFTCollectionCreatedEvent.InputTuple,
      NFTCollectionCreatedEvent.OutputTuple,
      NFTCollectionCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
