/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SP1Verifier {
  export type CarbonIndexProofStruct = {
    nhiScore: BigNumberish;
    p20Percentile: BigNumberish;
    p90Percentile: BigNumberish;
    gammaShape: BigNumberish;
    gammaScale: BigNumberish;
    gammaLoc: BigNumberish;
    carbonIndexValue: BigNumberish;
    timestamp: BigNumberish;
    latMin: BigNumberish;
    latMax: BigNumberish;
    lonMin: BigNumberish;
    lonMax: BigNumberish;
  };

  export type CarbonIndexProofStructOutput = [
    nhiScore: bigint,
    p20Percentile: bigint,
    p90Percentile: bigint,
    gammaShape: bigint,
    gammaScale: bigint,
    gammaLoc: bigint,
    carbonIndexValue: bigint,
    timestamp: bigint,
    latMin: bigint,
    latMax: bigint,
    lonMin: bigint,
    lonMax: bigint
  ] & {
    nhiScore: bigint;
    p20Percentile: bigint;
    p90Percentile: bigint;
    gammaShape: bigint;
    gammaScale: bigint;
    gammaLoc: bigint;
    carbonIndexValue: bigint;
    timestamp: bigint;
    latMin: bigint;
    latMax: bigint;
    lonMin: bigint;
    lonMax: bigint;
  };
}

export interface SP1VerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "VERIFICATION_KEY"
      | "finalizeProof"
      | "getCarbonIndexValue"
      | "getProofData"
      | "getZKVerifyProofId"
      | "isProofSubmitted"
      | "isProofVerified"
      | "owner"
      | "proofData"
      | "proofIdByHash"
      | "proofSubmitted"
      | "renounceOwnership"
      | "revokeProof"
      | "transferOwnership"
      | "updateVerificationKey"
      | "verifiedProofs"
      | "verifyProof"
      | "zkVerify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProofRejected"
      | "ProofSubmittedToZKVerify"
      | "ProofVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "VERIFICATION_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCarbonIndexValue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getZKVerifyProofId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProofSubmitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProofVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proofData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proofIdByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proofSubmitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerificationKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, SP1Verifier.CarbonIndexProofStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "zkVerify", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "VERIFICATION_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCarbonIndexValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProofData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZKVerifyProofId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProofSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProofVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proofIdByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zkVerify", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofRejectedEvent {
  export type InputTuple = [proofHash: BytesLike, reason: string];
  export type OutputTuple = [proofHash: string, reason: string];
  export interface OutputObject {
    proofHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedToZKVerifyEvent {
  export type InputTuple = [proofHash: BytesLike, zkVerifyProofId: BytesLike];
  export type OutputTuple = [proofHash: string, zkVerifyProofId: string];
  export interface OutputObject {
    proofHash: string;
    zkVerifyProofId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    proofHash: BytesLike,
    carbonIndexValue: BigNumberish,
    timestamp: BigNumberish,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    proofHash: string,
    carbonIndexValue: bigint,
    timestamp: bigint,
    verifier: string
  ];
  export interface OutputObject {
    proofHash: string;
    carbonIndexValue: bigint;
    timestamp: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SP1Verifier extends BaseContract {
  connect(runner?: ContractRunner | null): SP1Verifier;
  waitForDeployment(): Promise<this>;

  interface: SP1VerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VERIFICATION_KEY: TypedContractMethod<[], [string], "view">;

  finalizeProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getCarbonIndexValue: TypedContractMethod<
    [proofHash: BytesLike],
    [bigint],
    "view"
  >;

  getProofData: TypedContractMethod<
    [proofHash: BytesLike],
    [SP1Verifier.CarbonIndexProofStructOutput],
    "view"
  >;

  getZKVerifyProofId: TypedContractMethod<
    [proofHash: BytesLike],
    [string],
    "view"
  >;

  isProofSubmitted: TypedContractMethod<
    [proofHash: BytesLike],
    [boolean],
    "view"
  >;

  isProofVerified: TypedContractMethod<
    [proofHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proofData: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        nhiScore: bigint;
        p20Percentile: bigint;
        p90Percentile: bigint;
        gammaShape: bigint;
        gammaScale: bigint;
        gammaLoc: bigint;
        carbonIndexValue: bigint;
        timestamp: bigint;
        latMin: bigint;
        latMax: bigint;
        lonMin: bigint;
        lonMax: bigint;
      }
    ],
    "view"
  >;

  proofIdByHash: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  proofSubmitted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateVerificationKey: TypedContractMethod<
    [newVerificationKey: BytesLike],
    [void],
    "nonpayable"
  >;

  verifiedProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyProof: TypedContractMethod<
    [
      proof: BytesLike,
      publicValues: SP1Verifier.CarbonIndexProofStruct,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  zkVerify: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VERIFICATION_KEY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCarbonIndexValue"
  ): TypedContractMethod<[proofHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProofData"
  ): TypedContractMethod<
    [proofHash: BytesLike],
    [SP1Verifier.CarbonIndexProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getZKVerifyProofId"
  ): TypedContractMethod<[proofHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isProofSubmitted"
  ): TypedContractMethod<[proofHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProofVerified"
  ): TypedContractMethod<[proofHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofData"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        nhiScore: bigint;
        p20Percentile: bigint;
        p90Percentile: bigint;
        gammaShape: bigint;
        gammaScale: bigint;
        gammaLoc: bigint;
        carbonIndexValue: bigint;
        timestamp: bigint;
        latMin: bigint;
        latMax: bigint;
        lonMin: bigint;
        lonMax: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofIdByHash"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "proofSubmitted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVerificationKey"
  ): TypedContractMethod<[newVerificationKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [
      proof: BytesLike,
      publicValues: SP1Verifier.CarbonIndexProofStruct,
      proofHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zkVerify"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofRejected"
  ): TypedContractEvent<
    ProofRejectedEvent.InputTuple,
    ProofRejectedEvent.OutputTuple,
    ProofRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmittedToZKVerify"
  ): TypedContractEvent<
    ProofSubmittedToZKVerifyEvent.InputTuple,
    ProofSubmittedToZKVerifyEvent.OutputTuple,
    ProofSubmittedToZKVerifyEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofRejected(bytes32,string)": TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;
    ProofRejected: TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;

    "ProofSubmittedToZKVerify(bytes32,bytes32)": TypedContractEvent<
      ProofSubmittedToZKVerifyEvent.InputTuple,
      ProofSubmittedToZKVerifyEvent.OutputTuple,
      ProofSubmittedToZKVerifyEvent.OutputObject
    >;
    ProofSubmittedToZKVerify: TypedContractEvent<
      ProofSubmittedToZKVerifyEvent.InputTuple,
      ProofSubmittedToZKVerifyEvent.OutputTuple,
      ProofSubmittedToZKVerifyEvent.OutputObject
    >;

    "ProofVerified(bytes32,uint256,uint256,address)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
  };
}
