/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZKVerify {
  export type ProofStatusStruct = {
    submitted: boolean;
    verified: boolean;
    submissionTime: BigNumberish;
    verificationTime: BigNumberish;
    errorMessage: string;
  };

  export type ProofStatusStructOutput = [
    submitted: boolean,
    verified: boolean,
    submissionTime: bigint,
    verificationTime: bigint,
    errorMessage: string
  ] & {
    submitted: boolean;
    verified: boolean;
    submissionTime: bigint;
    verificationTime: bigint;
    errorMessage: string;
  };
}

export interface IZKVerifyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProofStatus"
      | "getVerificationFee"
      | "isAcceptingSubmissions"
      | "submitProof"
      | "verifyProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProofSubmitted" | "ProofVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getProofStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAcceptingSubmissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getProofStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAcceptingSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [proofId: BytesLike, submitter: AddressLike];
  export type OutputTuple = [proofId: string, submitter: string];
  export interface OutputObject {
    proofId: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [proofId: BytesLike, verified: boolean];
  export type OutputTuple = [proofId: string, verified: boolean];
  export interface OutputObject {
    proofId: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IZKVerify extends BaseContract {
  connect(runner?: ContractRunner | null): IZKVerify;
  waitForDeployment(): Promise<this>;

  interface: IZKVerifyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProofStatus: TypedContractMethod<
    [proofId: BytesLike],
    [IZKVerify.ProofStatusStructOutput],
    "view"
  >;

  getVerificationFee: TypedContractMethod<[], [bigint], "view">;

  isAcceptingSubmissions: TypedContractMethod<[], [boolean], "view">;

  submitProof: TypedContractMethod<
    [proof: BytesLike, publicInputs: BytesLike],
    [string],
    "nonpayable"
  >;

  verifyProof: TypedContractMethod<[proofId: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProofStatus"
  ): TypedContractMethod<
    [proofId: BytesLike],
    [IZKVerify.ProofStatusStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAcceptingSubmissions"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [proof: BytesLike, publicInputs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<[proofId: BytesLike], [boolean], "view">;

  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;

  filters: {
    "ProofSubmitted(bytes32,address)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "ProofVerified(bytes32,bool)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
  };
}
