/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace NatureIndexTracker {
  export type IndexSnapshotStruct = {
    timestamp: BigNumberish;
    geoIndexValue: BigNumberish;
    natureUnitPrice: BigNumberish;
    computedValue: BigNumberish;
  };

  export type IndexSnapshotStructOutput = [
    timestamp: bigint,
    geoIndexValue: bigint,
    natureUnitPrice: bigint,
    computedValue: bigint
  ] & {
    timestamp: bigint;
    geoIndexValue: bigint;
    natureUnitPrice: bigint;
    computedValue: bigint;
  };
}

export interface NatureIndexTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeCurrentValue"
      | "conversionRate"
      | "convertGeoIndexToNatureUnits"
      | "convertNatureUnitsToValue"
      | "createSnapshot"
      | "externalOracle"
      | "geoIndexToken"
      | "getCurrentGeoIndexValue"
      | "getCurrentNatureUnitPrice"
      | "getCurrentState"
      | "getLatestSnapshot"
      | "getSnapshot"
      | "owner"
      | "priceMultiplier"
      | "renounceOwnership"
      | "setConversionRate"
      | "setExternalOracle"
      | "setGeoIndexToken"
      | "setPriceMultiplier"
      | "snapshotCount"
      | "snapshots"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConversionRateUpdated"
      | "ExternalOracleUpdated"
      | "GeoIndexTokenUpdated"
      | "OwnershipTransferred"
      | "PriceMultiplierUpdated"
      | "SnapshotCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "computeCurrentValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conversionRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertGeoIndexToNatureUnits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertNatureUnitsToValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "externalOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "geoIndexToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentGeoIndexValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentNatureUnitPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSnapshot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setConversionRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExternalOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGeoIndexToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshotCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "snapshots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeCurrentValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conversionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertGeoIndexToNatureUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertNatureUnitsToValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "geoIndexToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentGeoIndexValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentNatureUnitPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConversionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExternalOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGeoIndexToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snapshotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConversionRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExternalOracleUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GeoIndexTokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceMultiplierUpdatedEvent {
  export type InputTuple = [
    oldMultiplier: BigNumberish,
    newMultiplier: BigNumberish
  ];
  export type OutputTuple = [oldMultiplier: bigint, newMultiplier: bigint];
  export interface OutputObject {
    oldMultiplier: bigint;
    newMultiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotCreatedEvent {
  export type InputTuple = [
    snapshotId: BigNumberish,
    geoIndexValue: BigNumberish,
    natureUnitPrice: BigNumberish,
    computedValue: BigNumberish
  ];
  export type OutputTuple = [
    snapshotId: bigint,
    geoIndexValue: bigint,
    natureUnitPrice: bigint,
    computedValue: bigint
  ];
  export interface OutputObject {
    snapshotId: bigint;
    geoIndexValue: bigint;
    natureUnitPrice: bigint;
    computedValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NatureIndexTracker extends BaseContract {
  connect(runner?: ContractRunner | null): NatureIndexTracker;
  waitForDeployment(): Promise<this>;

  interface: NatureIndexTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeCurrentValue: TypedContractMethod<[], [bigint], "view">;

  conversionRate: TypedContractMethod<[], [bigint], "view">;

  convertGeoIndexToNatureUnits: TypedContractMethod<
    [geoIndexValue: BigNumberish],
    [bigint],
    "view"
  >;

  convertNatureUnitsToValue: TypedContractMethod<
    [natureUnits: BigNumberish],
    [bigint],
    "view"
  >;

  createSnapshot: TypedContractMethod<[], [bigint], "nonpayable">;

  externalOracle: TypedContractMethod<[], [string], "view">;

  geoIndexToken: TypedContractMethod<[], [string], "view">;

  getCurrentGeoIndexValue: TypedContractMethod<[], [bigint], "view">;

  getCurrentNatureUnitPrice: TypedContractMethod<[], [bigint], "view">;

  getCurrentState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        geoIndexValue: bigint;
        natureUnitPrice: bigint;
        computedValue: bigint;
        natureUnitsEquivalent: bigint;
        lastSnapshotId: bigint;
      }
    ],
    "view"
  >;

  getLatestSnapshot: TypedContractMethod<
    [],
    [NatureIndexTracker.IndexSnapshotStructOutput],
    "view"
  >;

  getSnapshot: TypedContractMethod<
    [snapshotId: BigNumberish],
    [NatureIndexTracker.IndexSnapshotStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceMultiplier: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setConversionRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExternalOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setGeoIndexToken: TypedContractMethod<
    [newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceMultiplier: TypedContractMethod<
    [newMultiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  snapshotCount: TypedContractMethod<[], [bigint], "view">;

  snapshots: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        timestamp: bigint;
        geoIndexValue: bigint;
        natureUnitPrice: bigint;
        computedValue: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeCurrentValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "conversionRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertGeoIndexToNatureUnits"
  ): TypedContractMethod<[geoIndexValue: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertNatureUnitsToValue"
  ): TypedContractMethod<[natureUnits: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createSnapshot"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "externalOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "geoIndexToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentGeoIndexValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentNatureUnitPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        geoIndexValue: bigint;
        natureUnitPrice: bigint;
        computedValue: bigint;
        natureUnitsEquivalent: bigint;
        lastSnapshotId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestSnapshot"
  ): TypedContractMethod<
    [],
    [NatureIndexTracker.IndexSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSnapshot"
  ): TypedContractMethod<
    [snapshotId: BigNumberish],
    [NatureIndexTracker.IndexSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConversionRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExternalOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGeoIndexToken"
  ): TypedContractMethod<[newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceMultiplier"
  ): TypedContractMethod<[newMultiplier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "snapshotCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "snapshots"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        timestamp: bigint;
        geoIndexValue: bigint;
        natureUnitPrice: bigint;
        computedValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConversionRateUpdated"
  ): TypedContractEvent<
    ConversionRateUpdatedEvent.InputTuple,
    ConversionRateUpdatedEvent.OutputTuple,
    ConversionRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExternalOracleUpdated"
  ): TypedContractEvent<
    ExternalOracleUpdatedEvent.InputTuple,
    ExternalOracleUpdatedEvent.OutputTuple,
    ExternalOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GeoIndexTokenUpdated"
  ): TypedContractEvent<
    GeoIndexTokenUpdatedEvent.InputTuple,
    GeoIndexTokenUpdatedEvent.OutputTuple,
    GeoIndexTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceMultiplierUpdated"
  ): TypedContractEvent<
    PriceMultiplierUpdatedEvent.InputTuple,
    PriceMultiplierUpdatedEvent.OutputTuple,
    PriceMultiplierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SnapshotCreated"
  ): TypedContractEvent<
    SnapshotCreatedEvent.InputTuple,
    SnapshotCreatedEvent.OutputTuple,
    SnapshotCreatedEvent.OutputObject
  >;

  filters: {
    "ConversionRateUpdated(uint256,uint256)": TypedContractEvent<
      ConversionRateUpdatedEvent.InputTuple,
      ConversionRateUpdatedEvent.OutputTuple,
      ConversionRateUpdatedEvent.OutputObject
    >;
    ConversionRateUpdated: TypedContractEvent<
      ConversionRateUpdatedEvent.InputTuple,
      ConversionRateUpdatedEvent.OutputTuple,
      ConversionRateUpdatedEvent.OutputObject
    >;

    "ExternalOracleUpdated(address,address)": TypedContractEvent<
      ExternalOracleUpdatedEvent.InputTuple,
      ExternalOracleUpdatedEvent.OutputTuple,
      ExternalOracleUpdatedEvent.OutputObject
    >;
    ExternalOracleUpdated: TypedContractEvent<
      ExternalOracleUpdatedEvent.InputTuple,
      ExternalOracleUpdatedEvent.OutputTuple,
      ExternalOracleUpdatedEvent.OutputObject
    >;

    "GeoIndexTokenUpdated(address,address)": TypedContractEvent<
      GeoIndexTokenUpdatedEvent.InputTuple,
      GeoIndexTokenUpdatedEvent.OutputTuple,
      GeoIndexTokenUpdatedEvent.OutputObject
    >;
    GeoIndexTokenUpdated: TypedContractEvent<
      GeoIndexTokenUpdatedEvent.InputTuple,
      GeoIndexTokenUpdatedEvent.OutputTuple,
      GeoIndexTokenUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceMultiplierUpdated(uint256,uint256)": TypedContractEvent<
      PriceMultiplierUpdatedEvent.InputTuple,
      PriceMultiplierUpdatedEvent.OutputTuple,
      PriceMultiplierUpdatedEvent.OutputObject
    >;
    PriceMultiplierUpdated: TypedContractEvent<
      PriceMultiplierUpdatedEvent.InputTuple,
      PriceMultiplierUpdatedEvent.OutputTuple,
      PriceMultiplierUpdatedEvent.OutputObject
    >;

    "SnapshotCreated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      SnapshotCreatedEvent.InputTuple,
      SnapshotCreatedEvent.OutputTuple,
      SnapshotCreatedEvent.OutputObject
    >;
    SnapshotCreated: TypedContractEvent<
      SnapshotCreatedEvent.InputTuple,
      SnapshotCreatedEvent.OutputTuple,
      SnapshotCreatedEvent.OutputObject
    >;
  };
}
