/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInputOracle,
  IInputOracleInterface,
} from "../../../contracts/NFTVault.sol/IInputOracle";

const _abi = [
  {
    inputs: [],
    name: "latest",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IInputOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IInputOracleInterface {
    return new Interface(_abi) as IInputOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInputOracle {
    return new Contract(address, _abi, runner) as unknown as IInputOracle;
  }
}
