/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IInputOracle__factory } from "./IInputOracle__factory";
export { NFTVault__factory } from "./NFTVault__factory";
